### ISSUE TITLE
trezor when sending payouts: RuntimeError: DataError: Encountered invalid prevhash

### ISSUE THREAD

**Issue by molecular** [akhavr/electrum-dash#100]
I'm using trezor to receive payouts from my masternode. When I try to spend any of those payout utxos I get the following exception:

```
E | gui.qt.main_window.[trezor_rz3.account_5] | on_error
Traceback (most recent call last):
  File "/home/nick/bitcoin/electrum-dash/electrum_dash/plugins/trezor/clientbase.py", line 224, in sign_tx
    return trezorlib.btc.sign_tx(self.client, *args, **kwargs)
  File "/home/nick/bitcoin/electrum-dash/packages/trezorlib/tools.py", line 233, in wrapped_f
    return f(client, *args, **kwargs)
  File "/home/nick/bitcoin/electrum-dash/packages/trezorlib/btc.py", line 176, in sign_tx
    res = client.call(messages.TxAck(tx=msg))
  File "/home/nick/bitcoin/electrum-dash/packages/trezorlib/tools.py", line 233, in wrapped_f
    return f(client, *args, **kwargs)
  File "/home/nick/bitcoin/electrum-dash/packages/trezorlib/client.py", line 222, in call
    raise exceptions.TrezorFailure(resp)
trezorlib.exceptions.TrezorFailure: DataError: Encountered invalid prevhash

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nick/bitcoin/electrum-dash/electrum_dash/gui/qt/util.py", line 723, in run
    result = task.task()
  File "/home/nick/bitcoin/electrum-dash/electrum_dash/wallet.py", line 948, in sign_transaction
    k.sign_transaction(tx, password)
  File "/home/nick/bitcoin/electrum-dash/electrum_dash/plugins/trezor/trezor.py", line 91, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/home/nick/bitcoin/electrum-dash/electrum_dash/plugins/trezor/trezor.py", line 328, in sign_transaction
    signatures, _ = client.sign_tx(self.get_coin_name(), inputs, outputs, details=details, prev_txes=prev_tx)
  File "/home/nick/bitcoin/electrum-dash/electrum_dash/plugins/trezor/clientbase.py", line 224, in sign_tx
    return trezorlib.btc.sign_tx(self.client, *args, **kwargs)
  File "/home/nick/bitcoin/electrum-dash/electrum_dash/plugins/trezor/clientbase.py", line 74, in __exit__
    raise RuntimeError(str(e)) from e
RuntimeError: DataError: Encountered invalid prevhash
```

Not sure what to make of it or where the culprit lies.

using trezor lib version 0.11.5. (requirements-hw.txt says >=0.11.0 is fine)

spending those same utxos works fine using other wallet software (wallet.trezor.io and DashMasternodeTool for example)

any ideas?

**Comment by molecular** [comment]
find similar issue in old repo: https://github.com/dashpay/electrum-dash-old/issues/104. no answers there, though.

**Comment by akhavr** [comment]
Sorry, we've been defunded, so we are supporting Dash Electrum only as time allows.

**Comment by molecular** [comment]
ok, I understand. Looking at some of the discussion it seems some don't like to spend that much on what they see as a "legacy wallet". Instead of new features, it seems they'd rather see a much less costly "maintenance mode" for electrum-dash. Is this something you would consider doing?

**Comment by akhavr** [comment]
This issue is back in our pipeline.

**Comment by akhavr** [comment]
The fix will be in the next update.  Reopen if it won't work.

**Comment by molecular** [comment]
ok, I'll happily retest. When will the release be out? There's nothing new on the master branch.

**Comment by akhavr** [comment]
@molecular checkout the release branch, or we can make a custom build for you, or just wait for the release :)

**Comment by molecular** [comment]
@akhavr retested on tag 3.3.8.4 and IT WORKS!!!

thank you so much. Will send a donation.

**Comment by akhavr** [comment]
Feel free to drop some love at XydGywi8gWCcQKpri8vUUmtrGwnywBXXit :)
