### ISSUE TITLE
Cannot import name 'SocksConnector' from 'aiohttp_socks'

### ISSUE THREAD

**Issue by venomone** [akhavr/electrum-dash#124]
Hello,

since a couple of days I'm experiencing the following issue if i do:
```

  echo "Restoring wallet(s) as read-only from Master Public Key"
  {
  electrum-dash restore $DASH_WALLET_MPK
  }
```

I Install electrum-dash like so:

pip3 install https://mydomain.com/Dash-Electrum-3.3.8.6.tar.gz#egg=dash-electrum

-> results in:

> Traceback (most recent call last):
> File "/usr/local/bin/electrum-dash", line 82, in <module>
>    from electrum_dash.logging import get_logger, configure_logging
> File "/usr/local/lib/python3.8/site-packages/electrum_dash/__init__.py", line 2, in <module>
>     from .util import format_satoshis
> File "/usr/local/lib/python3.8/site-packages/electrum_dash/util.py", line 45, in <module>
>     from aiohttp_socks import SocksConnector, SocksVer
> ImportError: cannot import name 'SocksConnector' from 'aiohttp_socks' (/usr/local/lib/python3.8/site-packages/aiohttp_socks/__init__.py)

Where does this issue comes from?

**Comment by venomone** [comment]
Doing pip3 install aiohttp_socks==0.4.2 seems to solve the issue since the dev. of aiohttp_socks has pushed an update about 14 hrs ago!

**Comment by venomone** [comment]
v0.5.2 of aiohttp-socks solves the issue, has been release today (GMT)
