### ISSUE TITLE
RecursionError in get_verified_tx

### ISSUE THREAD

**Issue by zebra-lucky** [akhavr/electrum-dash#231]
```
Traceback (most recent call last):
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/electrum_dash/gui/qt/protx_wizards.py", line 1067, in frozen_state_changed
    self.scan_for_outputs()
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/electrum_dash/gui/qt/protx_wizards.py", line 1082, in scan_for_outputs
    mature_only=True, confirmed_only=True)
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/electrum_dash/address_synchronizer.py", line 544, in f
    return func(self, *args, **kwargs)
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/electrum_dash/address_synchronizer.py", line 1029, in get_utxos
    utxos = self.get_addr_utxo(addr)
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/electrum_dash/address_synchronizer.py", line 946, in get_addr_utxo
    out = self.get_addr_outputs(address)
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/electrum_dash/address_synchronizer.py", line 908, in get_addr_outputs
    coins, spent = self.get_addr_io(address)
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/electrum_dash/address_synchronizer.py", line 893, in get_addr_io
    h = self.get_address_history(address)
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/electrum_dash/address_synchronizer.py", line 147, in get_address_history
    tx_height = self.get_tx_height(tx_hash).height
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/electrum_dash/address_synchronizer.py", line 772, in get_tx_height
    verified_tx_mined_info = self.db.get_verified_tx(tx_hash)
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/electrum_dash/json_db.py", line 44, in wrapper
    return func(self, *args, **kwargs)
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/electrum_dash/wallet_db.py", line 1305, in get_verified_tx
    assert isinstance(txid, str)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by zebra-lucky** [comment]
Resembles https://github.com/spesmilo/electrum/issues/4912

**Comment by zebra-lucky** [comment]
also resembles https://github.com/spesmilo/electrum/issues/4670
