### ISSUE TITLE
kivy: setting pin fail

### ISSUE THREAD

**Issue by zebra-lucky** [akhavr/electrum-dash#239]
In a prepared 4.1.2.0 setting pin fails with:

```python
E | daemon.Daemon | GUI raised exception: AttributeError("'super' object has no attribute '__getattr__'"). shutting down.
E | __main__ | daemon.run_gui errored
Traceback (most recent call last):
  File "kivy/properties.pyx", line 861, in kivy.properties.ObservableDict.__getattr__
KeyError: 'textinput_generic_password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./electrum-dash", line 450, in handle_cmd
    d.run_gui(config, plugins)
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/electrum_dash/daemon.py", line 559, in run_gui
    self.gui_object.main()
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/electrum_dash/gui/kivy/__init__.py", line 72, in main
    w.run()
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/env/lib/python3.7/site-packages/kivy/app.py", line 950, in run
    runTouchApp()
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/env/lib/python3.7/site-packages/kivy/base.py", line 582, in runTouchApp
    EventLoop.mainloop()
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/env/lib/python3.7/site-packages/kivy/base.py", line 347, in mainloop
    self.idle()
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/env/lib/python3.7/site-packages/kivy/base.py", line 391, in idle
    self.dispatch_input()
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/env/lib/python3.7/site-packages/kivy/base.py", line 342, in dispatch_input
    post_dispatch_input(*pop(0))
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/env/lib/python3.7/site-packages/kivy/base.py", line 308, in post_dispatch_input
    wid.dispatch('on_touch_up', me)
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/env/lib/python3.7/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
    self.dispatch('on_release')
  File "kivy/_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
  File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
  File "kivy/_event.pyx", line 1132, in kivy._event.EventObservers._dispatch
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/env/lib/python3.7/site-packages/kivy/lang/builder.py", line 57, in custom_callback
    exec(__kvlang__.co_value, idmap)
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/electrum_dash/gui/kivy/main.kv", line 334, in <module>
    self.parent.update_amount(self.text)
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/electrum_dash/gui/kivy/uix/dialogs/password_dialog.py", line 239, in update_password
    kb.password = text
  File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
  File "kivy/properties.pyx", line 498, in kivy.properties.Property.__set__
  File "kivy/properties.pyx", line 545, in kivy.properties.Property.set
  File "kivy/properties.pyx", line 600, in kivy.properties.Property.dispatch
  File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
  File "kivy/_event.pyx", line 1130, in kivy._event.EventObservers._dispatch
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/env/lib/python3.7/site-packages/kivy/lang/builder.py", line 57, in custom_callback
    exec(__kvlang__.co_value, idmap)
  File "<string>", line 119, in <module>
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/electrum_dash/gui/kivy/uix/dialogs/password_dialog.py", line 312, in on_password
    self.do_check(pw)
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/electrum_dash/gui/kivy/uix/dialogs/password_dialog.py", line 259, in do_check
    self.dismiss()
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/env/lib/python3.7/site-packages/kivy/uix/modalview.py", line 255, in dismiss
    if self.dispatch('on_dismiss') is True:
  File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/electrum_dash/gui/kivy/uix/dialogs/password_dialog.py", line 226, in on_dismiss
    self.ids.textinput_generic_password.focus = False
  File "kivy/properties.pyx", line 864, in kivy.properties.ObservableDict.__getattr__
AttributeError: 'super' object has no attribute '__getattr__'
```

**Comment by zebra-lucky** [comment]
fixed in #240
