### ISSUE TITLE
Trying to spend Other PS coin from popup menu crashes

### ISSUE THREAD

**Issue by zebra-lucky** [akhavr/electrum-dash#297]
Trying to spend other PS coin from coins tab with popup menu "Spend" raises TypeError:

```
Traceback (most recent call last):
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/electrum_dash/gui/qt/utxo_list.py", line 530, in <lambda>
    menu.addAction(_("Spend"), lambda: self.set_spend_list(coins))
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/electrum_dash/gui/qt/utxo_list.py", line 457, in set_spend_list
    self.parent.send_vars_cb.set_from_coins(coins)
  File "/home/max/tmp/electrum/electrum-dash-post-3.2.2/electrum_dash/gui/qt/dash_qt.py", line 106, in set_from_coins
    and min_ps_rounds >= self.mix_rounds):
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
```

**Comment by zebra-lucky** [comment]
I'm sorry, this problem arises in testing branch (not `master`).

Closing this.
