### ISSUE TITLE
Network not connected

### ISSUE THREAD

**Issue by xiangloong** [akhavr/electrum-dash#298]
![截屏2021-11-10 下午6 50 36](https://user-images.githubusercontent.com/10485813/141100529-2fd07a62-6d02-40a3-a096-69c1a4499caa.png)

always Network not connected. And can't broadcast the transaction.

**Comment by akhavr** [comment]
Quite strange.  Try connecting to `electrumx-mainnet.dash.org` by right-clicking on the respective line.  Also there are more servers available via Tor

**Comment by xiangloong** [comment]
The wallet log is as follows，Can you change the limit:

20211115T075350.423780Z |     INFO | electrum.dash_net.DashNet | ignore excess getmnlistd request
20211115T075350.495025Z |    ERROR | asyncio | Task exception was never retrieved
future: <Task finished coro=<SynchronizerBase._run_tasks() done, defined at electrum_dash/synchronizer.py:77> exception=RPCError(-32600, 'response too large (over 1,000,000 bytes')>
Traceback (most recent call last):
  File "electrum_dash/synchronizer.py", line 83, in _run_tasks
  File "aiorpcx/curio.py", line 255, in __aexit__
  File "aiorpcx/curio.py", line 213, in join
  File "electrum_dash/synchronizer.py", line 192, in _on_address_status
  File "electrum_dash/interface.py", line 968, in get_history_for_scripthash
  File "electrum_dash/interface.py", line 175, in send_request
  File "asyncio/tasks.py", line 414, in wait_for
  File "aiorpcx/session.py", line 537, in send_request
  File "aiorpcx/session.py", line 507, in _send_concurrent
aiorpcx.jsonrpc.RPCError: (-32600, 'response too large (over 1,000,000 bytes')
20211115T075350.495807Z |    ERROR | asyncio | Task exception was never retrieved
future: <Task finished coro=<SynchronizerBase._run_tasks() done, defined at electrum_dash/synchronizer.py:77> exception=RPCError(-32600, 'response too large (over 1,000,000 bytes')>
Traceback (most recent call last):
  File "electrum_dash/synchronizer.py", line 83, in _run_tasks
  File "aiorpcx/curio.py", line 255, in __aexit__
  File "aiorpcx/curio.py", line 213, in join
  File "electrum_dash/synchronizer.py", line 192, in _on_address_status
  File "electrum_dash/interface.py", line 968, in get_history_for_scripthash
  File "electrum_dash/interface.py", line 175, in send_request
  File "asyncio/tasks.py", line 414, in wait_for
  File "aiorpcx/session.py", line 537, in send_request
  File "aiorpcx/session.py", line 507, in _send_concurrent
aiorpcx.jsonrpc.RPCError: (-32600, 'response too large (over 1,000,000 bytes')

**Comment by nbit99** [comment]
> Quite strange. Try connecting to `electrumx-mainnet.dash.org` by right-clicking on the respective line. Also there are more servers available via Tor

The wallet can't conntect because the bug:

`20211115T075350.423780Z | INFO | electrum.dash_net.DashNet | ignore excess getmnlistd request
20211115T075350.495025Z | ERROR | asyncio | Task exception was never retrieved
future: <Task finished coro=<SynchronizerBase._run_tasks() done, defined at electrum_dash/synchronizer.py:77> exception=RPCError(-32600, 'response too large (over 1,000,000 bytes')>
Traceback (most recent call last):
File "electrum_dash/synchronizer.py", line 83, in _run_tasks
File "aiorpcx/curio.py", line 255, in aexit
File "aiorpcx/curio.py", line 213, in join
File "electrum_dash/synchronizer.py", line 192, in _on_address_status
File "electrum_dash/interface.py", line 968, in get_history_for_scripthash
File "electrum_dash/interface.py", line 175, in send_request
File "asyncio/tasks.py", line 414, in wait_for
File "aiorpcx/session.py", line 537, in send_request
File "aiorpcx/session.py", line 507, in _send_concurrent
aiorpcx.jsonrpc.RPCError: (-32600, 'response too large (over 1,000,000 bytes')
20211115T075350.495807Z | ERROR | asyncio | Task exception was never retrieved
future: <Task finished coro=<SynchronizerBase._run_tasks() done, defined at electrum_dash/synchronizer.py:77> exception=RPCError(-32600, 'response too large (over 1,000,000 bytes')>
Traceback (most recent call last):
File "electrum_dash/synchronizer.py", line 83, in _run_tasks
File "aiorpcx/curio.py", line 255, in aexit
File "aiorpcx/curio.py", line 213, in join
File "electrum_dash/synchronizer.py", line 192, in _on_address_status
File "electrum_dash/interface.py", line 968, in get_history_for_scripthash
File "electrum_dash/interface.py", line 175, in send_request
File "asyncio/tasks.py", line 414, in wait_for
File "aiorpcx/session.py", line 537, in send_request
File "aiorpcx/session.py", line 507, in _send_concurrent
aiorpcx.jsonrpc.RPCError: (-32600, 'response too large (over 1,000,000 bytes')`

**Comment by akhavr** [comment]
This is not a bug, put a protocol message.

Is there anything special with the addresses in your wallet?

**Comment by xiangloong** [comment]
No special address.
There are just too many transactions and the wallet file is too big.

Is there a good way I can open my wallet and transfer？

**Comment by xiangloong** [comment]
Or could the limits be changed again.

aiorpcx.jsonrpc.RPCError: (-32600, 'response too large (over 1,000,000 bytes')

**Comment by zebra-lucky** [comment]
This problem raised from ElectrumX server.

main problem is:
```aiorpcx.jsonrpc.RPCError: (-32600, 'response too large (over 1,000,000 bytes')```

Default limit on server output RPC data is `1000000` bytes.
If you get access to server, then you can fix it by setting environment var for ElectrumX run:
```MAX_SEND=5000000```.

If you have no acess to server, then you need to waith, when
https://github.com/akhavr/electrumx will be updated with raised `MAX_SEND` limit.

**Comment by xiangloong** [comment]
Problem solved. thank you
