### ISSUE TITLE
exception=RPCError(-32600, 'response too large (over 1,000,000 bytes')>

### ISSUE THREAD

**Issue by xiangloong** [akhavr/electrum-dash#299]
The wallet can't conntect because the bug:

20211115T075350.423780Z | INFO | electrum.dash_net.DashNet | ignore excess getmnlistd request
20211115T075350.495025Z | ERROR | asyncio | Task exception was never retrieved
future: <Task finished coro=<SynchronizerBase._run_tasks() done, defined at electrum_dash/synchronizer.py:77> exception=RPCError(-32600, 'response too large (over 1,000,000 bytes')>
Traceback (most recent call last):
File "electrum_dash/synchronizer.py", line 83, in _run_tasks
File "aiorpcx/curio.py", line 255, in aexit
File "aiorpcx/curio.py", line 213, in join
File "electrum_dash/synchronizer.py", line 192, in _on_address_status
File "electrum_dash/interface.py", line 968, in get_history_for_scripthash
File "electrum_dash/interface.py", line 175, in send_request
File "asyncio/tasks.py", line 414, in wait_for
File "aiorpcx/session.py", line 537, in send_request
File "aiorpcx/session.py", line 507, in _send_concurrent
aiorpcx.jsonrpc.RPCError: (-32600, 'response too large (over 1,000,000 bytes')
20211115T075350.495807Z | ERROR | asyncio | Task exception was never retrieved
future: <Task finished coro=<SynchronizerBase._run_tasks() done, defined at electrum_dash/synchronizer.py:77> exception=RPCError(-32600, 'response too large (over 1,000,000 bytes')>
Traceback (most recent call last):
File "electrum_dash/synchronizer.py", line 83, in _run_tasks
File "aiorpcx/curio.py", line 255, in aexit
File "aiorpcx/curio.py", line 213, in join
File "electrum_dash/synchronizer.py", line 192, in _on_address_status
File "electrum_dash/interface.py", line 968, in get_history_for_scripthash
File "electrum_dash/interface.py", line 175, in send_request
File "asyncio/tasks.py", line 414, in wait_for
File "aiorpcx/session.py", line 537, in send_request
File "aiorpcx/session.py", line 507, in _send_concurrent
aiorpcx.jsonrpc.RPCError: (-32600, 'response too large (over 1,000,000 bytes')

**Comment by zebra-lucky** [comment]
The problem and resolution for this issue desrcibed in this comment:
https://github.com/akhavr/electrum-dash/issues/298#issuecomment-980258406
