### ISSUE TITLE
AttributeError: module 'electrum_dash.plugins' has no attribute '__file__' 

### ISSUE THREAD

**Issue by venomone** [akhavr/electrum-dash#67]
Hello,

if i simply install electrum-dash in a python3.6 venv i get the following error if i try to call it for a new address from the cli with "electrum-dash createnewaddress":

pip install [https://github.com/akhavr/electrum-dash/releases/download/3.2.3.2/Dash-Electrum-3.2.3.2.tar.gz#egg=electrum[fast]](https://github.com/akhavr/electrum-dash/releases/download/3.2.3.2/Dash-Electrum-3.2.3.2.tar.gz#egg=electrum%5Bfast%5D)

full trace

```
(venv) user@user-wkst:~/Doc/PyCharm/MyProject pip install https://github.com/akhavr/electrum-dash/releases/download/3.2.4/Dash-Electrum-3.2.4.tar.gz#egg=electrum-dash[fast]
Collecting electrum-dash[fast] from https://github.com/akhavr/electrum-dash/releases/download/3.2.4/Dash-Electrum-3.2.4.tar.gz#egg=electrum-dash[fast]
  Downloading https://github.com/akhavr/electrum-dash/releases/download/3.2.4/Dash-Electrum-3.2.4.tar.gz (8.9MB)
    100% |████████████████████████████████| 8.9MB 3.0MB/s 
  Generating metadata for package electrum-dash produced metadata for project name dash-electrum. Fix your #egg=electrum-dash fragments.
Requirement already satisfied: pyaes>=0.1a1 in ./venv/lib/python3.6/site-packages (from dash-electrum) (1.6.1)
Requirement already satisfied: ecdsa>=0.9 in ./venv/lib/python3.6/site-packages (from dash-electrum) (0.13)
Requirement already satisfied: requests in ./venv/lib/python3.6/site-packages (from dash-electrum) (2.21.0)
Requirement already satisfied: qrcode in ./venv/lib/python3.6/site-packages (from dash-electrum) (6.1)
Requirement already satisfied: protobuf in ./venv/lib/python3.6/site-packages (from dash-electrum) (3.6.1)
Requirement already satisfied: dnspython in ./venv/lib/python3.6/site-packages (from dash-electrum) (1.16.0)
Requirement already satisfied: jsonrpclib-pelix in ./venv/lib/python3.6/site-packages (from dash-electrum) (0.4.0)
Requirement already satisfied: PySocks>=1.6.6 in ./venv/lib/python3.6/site-packages (from dash-electrum) (1.6.8)
Collecting typing>=3.0.0 (from dash-electrum)
  Using cached https://files.pythonhosted.org/packages/4a/bd/eee1157fc2d8514970b345d69cb9975dcd1e42cd7e61146ed841f6e68309/typing-3.6.6-py3-none-any.whl
Requirement already satisfied: pycryptodomex in ./venv/lib/python3.6/site-packages (from dash-electrum) (3.7.3)
Collecting x11_hash (from dash-electrum)
  Using cached https://files.pythonhosted.org/packages/1a/85/9b4058ef4a3a4678c2a039c59b07fb6003ccde2fd6a05cc5670da247ba4e/x11_hash-1.4.tar.gz
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./venv/lib/python3.6/site-packages (from requests->dash-electrum) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.6/site-packages (from requests->dash-electrum) (2018.11.29)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in ./venv/lib/python3.6/site-packages (from requests->dash-electrum) (1.24.1)
Requirement already satisfied: idna<2.9,>=2.5 in ./venv/lib/python3.6/site-packages (from requests->dash-electrum) (2.8)
Requirement already satisfied: six in ./venv/lib/python3.6/site-packages (from qrcode->dash-electrum) (1.12.0)
Requirement already satisfied: setuptools in ./venv/lib/python3.6/site-packages (from protobuf->dash-electrum) (40.8.0)
Installing collected packages: typing, x11-hash, dash-electrum
  Running setup.py install for x11-hash ... done
  Running setup.py install for dash-electrum ... done
Successfully installed dash-electrum-3.2.4 typing-3.6.6 x11-hash-1.4
(venv) user@user-wkst:~/Doc/PyCharm/MyProject$ electrum-dash create
Password (hit return if you do not wish to encrypt your wallet):
Your wallet generation seed is:
"exhibit focus toilet swear light chronic juice census hint fiction chief blossom"
Please keep it in a safe place; if you lose it, you will not be able to restore your wallet.
Wallet saved in '/home/user/.electrum-dash/wallets/default_wallet'

(venv) user@user-wkst:~/Doc/PyCharm/MyProject$ electrum-dash daemon start
starting daemon (PID 29818)
Traceback (most recent call last):
  File "/home/user/Doc/PyCharm/MyProject/venv/bin/electrum-dash", line 439, in <module>
    init_plugins(config, 'cmdline')
  File "/home/user/Doc/PyCharm/MyProject/venv/bin/electrum-dash", line 328, in init_plugins
    return Plugins(config, is_local or is_android, gui_name)
  File "/home/user/Doc/PyCharm/MyProject/venv/lib/python3.6/site-packages/electrum_dash/util.py", line 344, in <lambda>
    return lambda *args, **kw_args: do_profile(args, kw_args)
  File "/home/user/Doc/PyCharm/MyProject/venv/lib/python3.6/site-packages/electrum_dash/util.py", line 340, in do_profile
    o = func(*args, **kw_args)
  File "/home/user/Doc/PyCharm/MyProject/venv/lib/python3.6/site-packages/electrum_dash/plugin.py", line 50, in __init__
    self.pkgpath = os.path.dirname(plugins.__file__)
AttributeError: module 'electrum_dash.plugins' has no attribute '__file__'

```

**Comment by akhavr** [comment]
Hopefully you won't use the wallet with the seed above..

The quick fix is `touch /home/user/Doc/PyCharm/MyProject/venv/lib/python3.6/site-packages/electrum_dash/plugins/__init__.py`

Fixed in #70
