### ISSUE TITLE
UserWarning: TrezorClient mixins are not supported anymore => trezor not working

### ISSUE THREAD

**Issue by molecular** [akhavr/electrum-dash#77]
not sure what to make of this:

```
/usr/lib/python3.7/site-packages/trezorlib/client.py:368: UserWarning: TrezorClient mixins are not supported anymore
  warnings.warn("TrezorClient mixins are not supported anymore")
/usr/lib/python3.7/site-packages/trezorlib/client.py:101: UserWarning: UI class not supplied. This will probably crash soon.
  warnings.warn("UI class not supplied. This will probably crash soon.")
/usr/lib/python3.7/site-packages/trezorlib/client.py:287: UserWarning: TrezorClient mixins are not supported anymore
  warnings.warn("TrezorClient mixins are not supported anymore")
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/electrum_dash/gui/qt/util.py", line 672, in run
    result = task.task()
  File "/usr/lib/python3.7/site-packages/electrum_dash/plugins/trezor/trezor.py", line 150, in get_client
    client = devmgr.client_for_keystore(self, handler, keystore, force_pair)
  File "/usr/lib/python3.7/site-packages/electrum_dash/plugin.py", line 409, in client_for_keystore
    client = self.force_pair_xpub(plugin, handler, info, xpub, derivation, devices)
  File "/usr/lib/python3.7/site-packages/electrum_dash/plugin.py", line 454, in force_pair_xpub
    'receive will be unspendable.').format(plugin.device))
electrum_dash.plugin.DeviceUnpairableError: Dash Electrum cannot pair with your TREZOR.
```

gui says "cannot pair with your trezor"

this is on version 3.2.5.1, trezor lib version 0.11.2

any ideas?

**Comment by molecular** [comment]
from trezolib code:

```
class BaseClient:
    """Compatibility proxy for original BaseClient class.
    Prevents early crash in Electrum forks and possibly other software.
    """

    def __init__(self, *args, **kwargs):
        warnings.warn("TrezorClient mixins are not supported anymore")
        self.trezor_client = TrezorClient(*args, **kwargs)

    def __getattr__(self, key):
        return getattr(self.trezor_client, key)
```

seems electrum-dash is using a deprecated feature in trezorlib.

Which version of trezorlib do I need to downgrade to?

**Comment by molecular** [comment]
to answer my own question

> Which version of trezorlib do I need to downgrade to?

```pip install trezor==0.10.2```

**Comment by akhavr** [comment]
We use package versions, specified in `contrib/deterministic-build/requirements-hw.txt`

You can install them using `python3 -m pip install -t packages -r contrib/deterministic-build/requirements-hw.txt`

This will be reflected in the next README.rst update
